### ISSUE TITLE
Can't upload images to Drupal site

### ISSUE THREAD

**Issue by allisonmargaret** [Multepal/popolwuj#27]

**Comment by ontoligent** [comment]
What kind of error messages do you see? We may be  running out of space.

**Comment by allisonmargaret** [comment]
I cleared the issue. I don't know why it stopped working, or why it started again. But it's fine now.


Thanks,


Allison Margaret Bigelow
433 New Cabell Hall / PO Box 400777
Department of Spanish, Italian, and Portuguese
University of Virginia
Charlottesville, VA 22904
amb8fk@virginia.edu * +1.434.243.3371 (p)
http://spanitalport.as.virginia.edu/people/profile/amb8fk
________________________________

**Comment by ontoligent** [comment]
OK -- I saw that is was closed after I commented.

Rafael C. Alvarado, Ph.D.
Program Director, Data Science Institute
University of Virginia
Dell 2, Room 117
1 434 982 1029
@ontoligent

**Comment by allisonmargaret** [comment]
No worries. PS, how are we displaying Catherine's escolios? I don't see them here (https://multepal.github.io/popolwuj/)


Allison Margaret Bigelow
433 New Cabell Hall / PO Box 400777
Department of Spanish, Italian, and Portuguese
University of Virginia
Charlottesville, VA 22904
amb8fk@virginia.edu * +1.434.243.3371 (p)
http://spanitalport.as.virginia.edu/people/profile/amb8fk
________________________________

**Comment by ontoligent** [comment]
I have not added the escolios yet to the presentation. They are a different application than the PW itself, since they do not have the two column format.
